[project]
name = "unspotify"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mutagen>=1.47.0",
    "pytube>=15.0.0",
    "spotipy>=2.25.1",
    "yt-dlp>=2025.2.19",
]
